x-redash-service: &redash-service
  image: redash/redash:10.0.0.b50363
  depends_on:
    - postgres
    - redis
  env_file: ./env
  restart: always
services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5001:5000"
    environment:
      REDASH_WEB_WORKERS: 4
    links:
      - postgres:postgres
  scheduler:
    <<: *redash-service
    command: scheduler
    # environment:
      # QUEUES: "celery"
      # WORKERS_COUNT: 1
  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1
  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2
  worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "periodic emails default"
      WORKERS_COUNT: 1
  redis:
    image: redis:7-alpine
    restart: always
  postgres:
    image: postgres:14-alpine
    env_file: ./env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
  nginx:
    image: redash/nginx:latest
    ports:
      - "8000:80"
    depends_on:
      - server
    links:
      - server:redash
    restart: always
